- charts/dt-kubewatch/Chart.yaml
- charts/dt-kubewatch/README.md
- charts/dt-kubewatch/templates/generic.yaml
- charts/dt-kubewatch/values.yaml
Devtron kubewatch helm chart added
> FEAT: Devtron kubewatch helm chart added

- charts/devtron/values.yaml
Bug has been fixed in values.yaml file.
> DOCS: Bug fixed in values.yaml

- charts/dt-kubewatch/Chart.yaml
- charts/dt-kubewatch/templates/generic.yaml
- charts/dt-kubewatch/values.yaml
Updated values.yaml and generic.yaml for the dt-kubewatch chart. Also updated the chart version
> Updated kubewatch values

- charts/dt-kubewatch/Chart.yaml
- charts/dt-kubewatch/templates/generic.yaml
- charts/dt-kubewatch/values.yaml
Added common Pod Labels for deployment and pods
> Added common pod labels

- charts/clair/Chart.yaml
- charts/clair/templates/_config.yaml.tpl
- charts/clair/templates/_helpers.tpl
- charts/clair/templates/deployment.yaml
- charts/clair/templates/ingress.yaml
- charts/clair/templates/secret.yaml
- charts/clair/templates/service.yaml
- charts/clair/values.yaml
- charts/gitsensor/Chart.yaml
- charts/gitsensor/README.md
- charts/gitsensor/templates/_helpers.tpl
- charts/gitsensor/templates/generic.yaml
- charts/gitsensor/templates/servicemonitor.yaml
- charts/gitsensor/values.yaml
- charts/nats-server/Chart.yaml
- charts/nats-server/README.md
- charts/nats-server/templates/nats.yaml
- charts/nats-server/values.yaml
- charts/nats-streaming/Chart.yaml
- charts/nats-streaming/LICENSE
- charts/nats-streaming/README.md
- charts/nats-streaming/templates/NOTES.txt
- charts/nats-streaming/templates/_helpers.tpl
- charts/nats-streaming/templates/monitoring-svc.yaml
- charts/nats-streaming/templates/networkpolicy.yaml
- charts/nats-streaming/templates/statefulset.yaml
- charts/nats-streaming/values.yaml
Added clair, git-sensor, nats-server, nats-streaming charts.
> added clair, git-sensor, nats-server, nats-streaming charts

- charts/gitsensor/Chart.yaml
- charts/gitsensor/templates/generic.yaml
- charts/gitsensor/values.yaml
Added affinity options for the git-sensor statesfulset
> Added Affinity to git-sensor chart

- charts/devtron/Chart.yaml
Fixes devtron-labs/devtron#881
> New chart version for fixed crds issue

- charts/mautic/Chart.yaml
- charts/mautic/requirements.yaml
- charts/mautic/templates/deployment.yaml
- charts/mautic/templates/pvc.yaml
- charts/mautic/values.yaml
Added support for existingPVC and externalDB for mautic chart
> feat: Make mautic chart more dynamic

- charts/aws-ssm-agent-installer/Chart.yaml
- charts/aws-ssm-agent-installer/templates/daemonset.yaml
- charts/aws-ssm-agent-installer/values.yaml
Added imagePullSecrets to aws-ssm-agent-installer chart.
> Added imagePullSecrets to aws-ssm-agent-installer chart

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-aws.yaml
- charts/devtron-backups/templates/serviceaccount.yaml
- charts/devtron-backups/values.yaml
- charts/devtron/values.yaml
This chart enabled periodic backup of devtron and argocd for disaster management
> feat: Devtron backups helm chart

- charts/devtron/Chart.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/rbac.yaml
- charts/devtron/values.yaml
This PR fixes namespace filter API in hyperion mode
> fix: Updated hyperion and dashboard images to latest version

- charts/devtron/Chart.yaml
- charts/devtron/templates/rbac.yaml
- charts/devtron/values.yaml
- Updated hyperion to latest version
- Updated kubelink to latest version
- Updated dashboard to latest version
- Updated latest migration hashes
> Release: Updated hyperion to latest version

- charts/readme.md
Removed old readme details and listed all charts with their use cases.
> Chart: Chart Readme Update

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
- Updated kubelink to latest version
- Updated hyperion to latest version
- Updated Devtron release tag
- Updated migration hashes
- Updated dashboard to latest version
- Updated chart version
> Updated devtron & hyperion to latest version

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
- Updated hyperion to latest version
- Updated dashboard to latest version
- Updated kubelink to latest version
- Updated migration hashes
- Updated Chart version
> Updated hyperion and devtron to latest version

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
This PR rollbacks latest release to last version
> Rollback hyperion and devtron to latest version

- charts/dgraph/Chart.yaml
- charts/dgraph/templates/alpha/statefulset.yaml
- charts/dgraph/values.yaml
Query edge limit functionality in dgraph.
> Query edge limit dgraph

- charts/argo-workflow/Chart.yaml
- charts/argo-workflow/templates/deployment.yaml
- charts/argo-workflow/values.yaml
Update the docker image of quay in argo-workflow chart
> Update docker image to quay in argo-workflow chart

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
- Updated devtron LTAG
- Updated hyperion image
- Updated dashboard image
- Updated migration hashes
- Updated Chart version
> Updated hyperion to latest version

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
- Updated hyperion image
- Updated LTAG
- Updated dashboard image
- Updated kubelink image
- Updated chart version
> Updated devtron and hyperion to latest version

- charts/devtron/Chart.yaml
- charts/devtron/values.yaml
Updates in dashboard micro-service
> RELEASE: PR for v0.3.26

- charts/devtron/Chart.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/values.yaml
Updates in devtron micro-service
> RELEASE: PR for v0.3.27

- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/devtron-ingress.yaml
- charts/devtron/templates/devtron-service.yaml
- charts/devtron/values.yaml
Service and Ingress changes for devtron 2.0
> Changes for devtron2.0

- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/rbac.yaml
- charts/devtron/values.yaml
This PR fixes Upgrade to devtron2.0 with cicd from old devtron full stack
> Fix: Upgrade to devtron2.0 with cicd from old devtron full stack

- charts/devtron/Chart.yaml
- charts/devtron/templates/NOTES.txt
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/argocd-secret.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/devtron-ingress.yaml
- charts/devtron/templates/devtron-installer.yaml
- charts/devtron/templates/devtron-service.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/dex.yaml
- charts/devtron/templates/install.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/templates/production-overrides.yaml
- charts/devtron/templates/rbac.yaml
- charts/devtron/values.yaml
Updates in devtron micro-service
> RELEASE: PR for v0.4.0

- charts/devtron/Chart.yaml
- charts/devtron/templates/devtron-ingress.yaml
Regarding this issue
https://github.com/helm/helm/issues/8026
> Updated first if condition in devtron-ingress

- charts/clair/Chart.yaml
- charts/clair/templates/deployment.yaml
- charts/clair/values.yaml
- Added support for environment variables in clair
> Added support for environment variables in clair

- charts/clair/Chart.yaml
- charts/clair/templates/_config.yaml.tpl
- charts/clair/templates/deployment.yaml
- charts/clair/values.yaml
Added conditions for insecureTls and extraEnv in deployment.yaml also provided configurable path: parameter. 
Added extra config from clairv4 yaml in _config.yaml.tpl with configurable params.
Provided the default values for above changes in values.yaml
> Update in Clair Template 

- charts/discord-alertmanager/Chart.yaml
- charts/discord-alertmanager/README.md
- charts/discord-alertmanager/templates/deployment.yaml
- charts/discord-alertmanager/templates/service.yaml
- charts/discord-alertmanager/values.yaml
add the alert manager chart into chart repo
> added the discord alertmanager chart

- charts/rollout/Chart.yaml
- charts/rollout/templates/generic.yaml
- charts/rollout/values.yaml
Added support for:
- podLabels
- podAnnotations
- replicaCount
> Added support for pod labels and annotations on rollout chart

- charts/svn-git-sync/Chart.yaml
- charts/svn-git-sync/templates/deployment.yaml
- charts/svn-git-sync/values.yaml
Added support for:
- podLabels
- podAnnotations
Updated default image tag
> Added support for pod labels and annotations on git-svn-sync chart

- charts/svn-git-sync/Chart.yaml
- charts/svn-git-sync/templates/configmap-secret.yaml
- charts/svn-git-sync/templates/deployment.yaml
- charts/svn-git-sync/values.yaml
- Added support for custom branches in git-svn-sync chart
> Added support for custom branches in git-svn-sync chart

- charts/argocd-certificate-refresh/Chart.yaml
- charts/argocd-certificate-refresh/README.md
- charts/argocd-certificate-refresh/templates/cronjob.yaml
- charts/argocd-certificate-refresh/templates/role.yaml
- charts/argocd-certificate-refresh/templates/rolebinding.yaml
- charts/argocd-certificate-refresh/templates/serviceaccount.yaml
- charts/argocd-certificate-refresh/values.yaml
Give the support to deploy argocd certificate refresh cronjob in devtron chart
> added the argocd certificate refresh cron job

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-aws.yaml
- charts/devtron-backups/templates/serviceaccount.yaml
- charts/devtron-backups/values.yaml
Update the devtron-backups chart with encryption and backward compatibility of argocd.
> support for argocd and postgres backup with encryption and backward compatibity

- charts/clair/Chart.yaml
- charts/clair/templates/_config.yaml.tpl
- charts/clair/templates/deployment.yaml
- charts/clair/values.yaml
- Default values as well as config changes
> Clair chart changes for security integration

- charts/clair/Chart.yaml
Create release and tag for clair
> Bump clair version

- charts/security/Chart.yaml
- charts/security/templates/image-scanner.yaml
- charts/security/values.yaml
- Added image-scanner
- Added clair as dependency
> Added Security chart to enable security as an integration

- charts/security/Chart.yaml
- charts/security/values.yaml
Updated multi-arch image for image-scanner
> Updated multi-arch image for image-scanner

- charts/clair/Chart.yaml
- charts/clair/templates/deployment.yaml
- charts/clair/templates/ingress.yaml
- charts/clair/templates/secret.yaml
- charts/clair/templates/service.yaml
- charts/clair/values.yaml
> feat: updated labels in clair chart

- charts/security/Chart.yaml
- charts/security/templates/image-scanner.yaml
- charts/security/values.yaml
added labels in image-scanner.yaml file
> feat: added labels in image-scanner.yaml file

- charts/prom2teams/.helmignore
- charts/prom2teams/Chart.yaml
- charts/prom2teams/files/teams.j2
- charts/prom2teams/templates/NOTES.txt
- charts/prom2teams/templates/_helpers.tpl
- charts/prom2teams/templates/configmap.yaml
- charts/prom2teams/templates/deployment.yaml
- charts/prom2teams/templates/service.yaml
- charts/prom2teams/templates/tests/test-connection.yaml
- charts/prom2teams/values.yaml
Added prom2teams helm chart to Devtron repository
> feat: added prom2teams chart

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
- Updated Chart.yaml to fix and release authenticator
> fix: Release v0.6.8 with authenticator changes

- charts/aws-ssm-agent-installer/Chart.yaml
- charts/aws-ssm-agent-installer/templates/daemonset.yaml
- charts/aws-ssm-agent-installer/values.yaml
Added option to remove cronjob as sudo in ssm chart
> feat: Added option to remove cronjob as sudo

- .github/workflows/chart-test-2.yaml
- .github/workflows/helm-chart-lint.yaml
Hem charts linting mechanism when PR is raised.
> chore:  Helm charts validator

- charts/gitsensor/Chart.yaml
- charts/gitsensor/templates/generic.yaml
- charts/gitsensor/values.yaml
add securityContext in git sensor StatefulSet container and pod.
> feat: securityContext support in git sensor chart.

- charts/argo-workflow/Chart.yaml
- charts/argo-workflow/templates/cm.yaml
- charts/argo-workflow/values.yaml
updated imagePullPolicy for executor image to ifNotPresent
> feat: updated imagepullpolicy for executor image

- charts/twistlock-defender/Chart.yaml
- charts/twistlock-defender/templates/daemonset.yaml
- charts/twistlock-defender/templates/secret.yaml
- charts/twistlock-defender/templates/securitycontextconstraints.yaml
- charts/twistlock-defender/templates/serviceaccount.yaml
- charts/twistlock-defender/values.yaml
Updated twistlock-defender chart
> feat: Updated twistlock-defender chart

- charts/rollout/Chart.yaml
- charts/rollout/templates/generic.yaml
- charts/rollout/values.yaml
Added support for nodeSelector and extraArgs in rollout
> feat: Added support for nodeSelector and extraArgs in rollout

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/values.yaml
feat: adds Google Cloud Storage support in devtron backup helm chart
> feat: adds GCS support in devtron backup helm chart

- charts/winter-soldier/Chart.yaml
- charts/winter-soldier/values.yaml
- fix: image updated with bug for same day range 
- added logs
- released chart version 0.10.6
> fix: image updated with bug for same day range and added logs

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-aws.yaml
- charts/devtron-backups/templates/backup-on-azure.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/templates/serviceaccount.yaml
- charts/devtron-backups/values.yaml
1.added support for enable and disable postgres and argocd backup
2.added encryption support during push to azure container
> feat: added support for enable and disable postgres and argocd backup 

- charts/in-clustercd/Chart.yaml
- charts/in-clustercd/templates/rbac.yaml
- charts/in-clustercd/templates/serviceaccount.yaml
- charts/in-clustercd/values.yaml
We have added the support to create **ci-runner** service account and rbac for ci-runner use by Job workflow .
> feat: Added the support in cluster helm chart to execute Jobs in target clusters

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-aws.yaml
- charts/devtron-backups/templates/backup-on-azure.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/values.yaml
feat: taking postgres hostname from values instead of hardcoding in template
> feat: Exposed postgres hostname from values instead of hardcoding in template

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-aws.yaml
- charts/devtron-backups/templates/backup-on-azure.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/values.yaml
Exposed the init_container_image to configurable
> feat: exposing the init-container image

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/values.yaml
> feat: Syncing Repo from branch sync-2024-03-13-100213-1331953

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/templates/backup-on-s3.yaml
- charts/devtron-backups/values.yaml
Modified the gcloud command and handled the creation of aws/se credentials
> fix: Modified the gcloud storage command to gsutil 

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-gcp.yaml
- charts/devtron-backups/templates/backup-on-s3.yaml
- charts/devtron-backups/values.yaml
Modified the gcloud command.
Handled the aws secret creation for s3 backup.
> fix: Backup chart fixes

- charts/devtron-backups/Chart.yaml
- charts/devtron-backups/templates/backup-on-s3.yaml
fixed the typo in the devtron-backup chart.
> fix: Devtron backup chart fix

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/_helpers.tpl
- charts/devtron/templates/argocd-secret.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/workflow.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-06-07-141738-803e027
> Sync changes from sync-2024-06-07-141738-803e027

- charts/security/Chart.yaml
- charts/security/templates/_helpers.tpl
- charts/security/templates/image-scanner.yaml
> feat: added serviceaccount to image-scanner

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/_helpers.tpl
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/casbin.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/devtron-scc.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/dex.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/grafana.yaml
- charts/devtron/templates/install.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/templates/nats-server.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/templates/scoop.yaml
- charts/devtron/templates/workflow.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-09-23-164137-0b7fc34
> Sync changes from sync-2024-09-23-164137-0b7fc34

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-10-02-064835-6dc445d
> Sync changes from sync-2024-10-02-064835-6dc445d

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/grafana.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-11-06-163535-37eec3c
> Sync changes from sync-2024-11-06-163535-37eec3c

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-11-13-151113-a5956dd
> Sync changes from sync-2024-11-13-151113-a5956dd

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2024-12-27-151627-51b5463
> Sync changes from sync-2024-12-27-151627-51b5463

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2025-02-04-072211-d10a74b
> Sync changes from sync-2025-02-04-072211-d10a74b

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2025-02-05-165902-80e2f92
> Sync changes from sync-2025-02-05-165902-80e2f92

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/_helpers.tpl
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/casbin.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/dex.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/grafana.yaml
- charts/devtron/templates/install.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/templates/nats-server.yaml
- charts/devtron/templates/networkpolicies.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/templates/scoop.yaml
- charts/devtron/templates/workflow.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2025-02-21-170512-c14bc40
> Sync changes from sync-2025-02-21-170512-c14bc40

- charts/devtron/Chart.yaml
- charts/devtron/templates/kubewatch.yaml
This pull request syncs changes from sync-2025-02-25-074228-bf41af4
> misc: Sync changes from sync-2025-02-25-074228-bf41af4

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2025-02-25-130011-db05da2
> Sync changes from sync-2025-02-25-130011-db05da2

- charts/devtron/Chart.yaml
- charts/devtron/templates/postgresql.yaml
This pull request syncs changes from sync-2025-02-27-070122-20a96a9
> Sync changes from sync-2025-02-27-070122-20a96a9

- charts/eks-terraform-karpenter/Chart.yaml
- charts/eks-terraform-karpenter/templates/NOTES.txt
- charts/eks-terraform-karpenter/templates/_helpers.tpl
- charts/eks-terraform-karpenter/templates/gitrepo.yaml
- charts/eks-terraform-karpenter/templates/terraform.yaml
- charts/eks-terraform-karpenter/values.yaml
Chart containing terraform object to create eks cluster
> chore: eks-terraform-karpenter-chart

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/NOTES.txt
- charts/devtron/templates/casbin.yaml
- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/values.yaml
This pull request syncs changes from sync-2025-04-23-134031-53dade1
> Sync changes from sync-2025-04-23-134031-53dade1

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
This pull request syncs changes from https://github.com/devtron-labs/devtron.git for release 1.5.1.
> Sync changes from https://github.com/devtron-labs/devtron.git for release 1.5.1

- charts/devtron-enterprise/Chart.yaml
- charts/devtron-enterprise/devtron-bom.yaml
- charts/devtron-enterprise/devtron-images.txt.source
- charts/devtron-enterprise/values.yaml
> release: PR for 34.0.0

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/values.yaml
This pull request syncs changes from https://github.com/devtron-labs/devtron.git for release 1.6.0.
> Sync changes from https://github.com/devtron-labs/devtron.git for release 1.6.0

- charts/devtron-enterprise/Chart.yaml
- charts/devtron-enterprise/devtron-bom.yaml
- charts/devtron-enterprise/devtron-images.txt.source
- charts/devtron-enterprise/values.yaml
> release: PR for 35.0.0

- charts/devtron-enterprise/Chart.yaml
- charts/devtron-enterprise/devtron-bom.yaml
- charts/devtron-enterprise/devtron-images.txt.source
- charts/devtron-enterprise/installation-script
- charts/devtron-enterprise/values.yaml
> release: PR for 36.0.0

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/casbin.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/devtron-service.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/templates/rbac.yaml
- charts/devtron/templates/workflow.yaml
- charts/devtron/values.yaml
This pull request syncs changes from https://github.com/devtron-labs/devtron.git for release 1.7.0.
> Sync changes from https://github.com/devtron-labs/devtron.git for release 1.7.0

- charts/jaeger-opentelemetry/Chart.yaml
- charts/jaeger-opentelemetry/templates/StatefulSet.yaml
- charts/jaeger-opentelemetry/values.yaml
issue https://github.com/devtron-labs/sprint-tasks/issues/2505
> chore: Adding support for resource configuration  in Jaeger
